### ISSUE TITLE
ImuPreintegration::Integrate check dt failure

### ISSUE THREAD

**Issue by JanQuenzel** [versatran01/llol#5]
Hi there,

I was trying out your code with the provided data and repeatedly stumbled upon a failed check during ImuPreintegration:
[CHECK_GT(dt, 0);](https://github.com/versatran01/llol/blob/601ce0234571a7a144472dedba17e238e8c108ca/sv/llol/imu.cpp#L318)
Before the failed check there is a message regarding:
> "All imus are before time.... Imu buffer size is 30, and the last imu in buffer has time ..., t0 - imu1.time = 0.0518486, set ibuf to 29"

I could trace it back to [ImuQueue::IndexAfter](https://github.com/versatran01/llol/blob/601ce0234571a7a144472dedba17e238e8c108ca/sv/llol/imu.cpp#L222) returning `ibuf = size()-1` instead of `size()`, which would be needed in [ImuPreintegration::Compute](https://github.com/versatran01/llol/blob/601ce0234571a7a144472dedba17e238e8c108ca/sv/llol/imu.cpp#L269) to detect this case.
Setting `ibuf = size() `in that case would be an easy fix. The same check for `ibuf==size()` is also used in [Trajectory::UpdateBias](https://github.com/versatran01/llol/blob/601ce0234571a7a144472dedba17e238e8c108ca/sv/llol/traj.cpp#L179).
But I saw that `ImuQueue::IndexAfter` is also used in traj.cpp for [Trajectory::PredictNew](https://github.com/versatran01/llol/blob/601ce0234571a7a144472dedba17e238e8c108ca/sv/llol/traj.cpp#L74) and [Trajectory::PredictFull](https://github.com/versatran01/llol/blob/601ce0234571a7a144472dedba17e238e8c108ca/sv/llol/traj.cpp#L115) without a further check.

Hence, I was wondering what would be the appropriate fix for this bug or what should be done in the Predict functions.
If I understood correctly, than it would suffice to use in the predict functions the same check `ibuf==size()` and returning 0. Is that correct?

Best, Jan

**Comment by versatran01** [comment]
Try playing the bag at normal rate or slower.
